### ISSUE TITLE
log API

### ISSUE THREAD

**Issue by jedisct1** [avidal/fastlike#19]
The logging API is quite useful, especially for debugging.

There are only two functions, one to get a handle given a name, and the other one to write to a given handle.

Do you have specific plans for implementing it, such as really supporting multiple handlers?

Or would writing the logs to the instance logger, along with the logger name be good enough at least to have this API implemented?

**Comment by avidal** [comment]
I had plans to work on it and dictionaries today. I think both will be implemented like backends. Let me give it a shot and we'll see how ergonomic it is.

Maybe there's a default option that logs to stdout though with a logger name like you mentioned.

**Comment by jedisct1** [comment]
Sounds good!

By the way, some initial Zig bindings are available here: https://github.com/jedisct1/zigly

**Comment by avidal** [comment]
That's super cool. I know next to nothing about zig but this may be enough to get me playing around with it.

**Comment by avidal** [comment]
See #20
